:repo: theme-tool
:idprefix:
:hide-uri-scheme:
:numbered:
:max-width: 900px
:icons: font
:toc: macro
:toclevels: 4
ifdef::env-github,env-browser[:outfilesuffix: .asciidoc]
ifdef::env-github[]
:note-caption: :information_source:
:tip-caption: :bulb:
:important-caption: :fire:
:caution-caption: :warning:
:warning-caption: :no_entry:
endif::[]

# Contributing to Shabad OS Theme Tool

Thank you for your interest to participate in Shabad OS projects!

There are many ways for people to contribute, beyond writing code or programming, by: logging bugs, reporting issues, and creating suggestions. All of which can be done through link:https://github.com/ShabadOS/{repo}/issues/new/choose[creating a ticket] in our issue tracker.

This document is for developers or programmers that wish to write code and directly contribute to the source code of Shabad OS for Theme Tool.

toc::[id="toc"]

## Getting Started

If you wish to better understand how Shabad OS works or want to debug an issue: get the source, build it, and run it locally.

### Prerequisites

In order to download necessary tools, clone the repository, and install dependencies, you'll need network access.

You'll need the following:

* https://git-scm.com/[Git]
* https://nodejs.org/en/[Node.JS], x64, version `>= 12.x`

We currently use precompiled binaries. If we need to compile native Node modules in the future, we would include the following prerequisites. The following instructions are not required to build, run, package, or distribute Shabad OS for desktop.

.See prerequisites for compile tool chain
[%collapsible]
====
* https://www.python.org/downloads/release/python-2715/[Python], at least version 2.7 (version 3 is not supported)
+
NOTE: Windows users will automatically install Python 2.7 through installing `windows-build-tools` npm module (see below)
* A C/C++ compiler tool chain for your platform:
  
  ... Windows
    *** Start Powershell as Administrator.
    *** Run `npm install --global windows-build-tools --vs2015`. (Try the `--debug` flag or check https://github.com/felixrieseberg/windows-build-tools[Windows Build Tools] if you encounter any problems.)
    *** Restart your computer
+
WARNING: Make sure your profile path only contains ASCII letters, otherwise it can lead to node-gyp usage problems (https://github.com/nodejs/node-gyp/issues/297[nodejs/node-gyp issue #297])
+
NOTE: If you have Visual Studio 2019 installed, you may face issues when using the default version of `node-gyp`. You may need to follow the solutions in https://github.com/nodejs/node-gyp/issues/1747[nodejs/node-gyp issue #1747].
  
  ... macOS
    *** https://developer.apple.com/xcode/downloads/[Xcode] can be used to install Command Line Tools containing `gcc` and the related tool-chain containing `make`.
    *** Open a terminal and run `xcode-select --install`.
  
  ... Linux
    *** `make`, `pkg-config`, GCC or another compile tool-chain
    *** Building packages has not been tested, so requirements are unknown
====

### Build

Install and build all of the dependencies:

[source,shell]
----
cd theme-tool
npm i <1>
----
<1> installs dependencies

### Run

To spin up the development servers, run `npm start`, which will launch a theme tool on https://localhost:3000[port `3000`].

### Overview

This a create-react-app.

## Workflow

The general workflow of development is to choose an issue to work on, create a feature branch off `dev` branch, and submit a pull request. This model is shared across all repos in the Shabad OS organization.

IMPORTANT: Please see the shared docs for Workflow (Issue Tracking, Branching, and Pull Requests) in the link:https://github.com/ShabadOS/.github/wiki/How-to-Contribute#workflow[How To Contribute wiki article].

## Coding Guidelines

Our coding guidelines are also (mostly) shared across all repos in the Shabad OS organization. Aside from scope definitions (which are repo specific), the rest should be referenced in the wiki article.

IMPORTANT: Please see the shared docs for Coding Guidelines (Names, Comments, Style, Linting, and Commit Messages) in the link:https://github.com/ShabadOS/.github/wiki/How-to-Contribute#coding-guidelines[How to Contribute wiki article].

## Thank you!

Your contributions to open source, large or small, make great projects like this possible. Thank you for taking the time to participate in this project.